version: "3.7"
services:
  app:
    build:
      args:
        user: joaquim
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: conversor-de-arquivos
    container_name: conversor-de-arquivos-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - conversor-de-arquivos

  nginx:
    image: nginx:alpine
    container_name: conversor-de-arquivos-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - conversor-de-arquivos
    depends_on:
      - app

networks:
  conversor-de-arquivos:
    driver: bridge
